baseURL = "http://jjerome.com/"
languageCode = "en-us"
title = "Jason Jerome"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Jason Jerome"
    description = ""
    githubUsername = "#"
    accent = "red"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

# [[menu.main]]
#     url = "/projects/"
#     name = "Projects"
#     weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1

[[menu.icon]]
    url = "https://github.com/jjerome00/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jjerome/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jason-jerome-475b673/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/103131/jj"
    name = "stack-overflow"
    weight = 5
